name: 'publish'
on:
  push:
    branches:
      - release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

jobs:
#  tests:
#    permissions:
#      contents: read
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: setup node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - name: install frontend dependencies
#        run: npm ci
#      - name: Running tests
#        run: npm run test
  publish-tauri:
#    needs: tests
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest, windows-latest] # ubuntu-20.04, not supported yet

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Add aarch-64 target (Mac only)
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin
      - name: install frontend dependencies
        run: npm install # change this to npm or pnpm depending on which one you usep
      - name: Build tauri app (Mac)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: 'Bug fixes and improvements!'
          releaseDraft: true
          prerelease: false
          args: '--target universal-apple-darwin'
      - name: Build tauri app (Windows)
        if: matrix.platform == 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: 'Bug fixes and improvements!'
          releaseDraft: true
          prerelease: false
